name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.2

      - name: Get firebase credentials
        run: |
          mkdir credentials
          echo $ENV_FILE > credentials/yarnswap-firebase.json
          cat credentials/yarnswap-firebase.json
        shell: bash
        env:
          ENV_FILE: ${{secrets.YARNSWAP_FIREBASE}}

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...